
import 'package:flutter/material.dart';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebasetest/core/model/postmodel.dart';

class yatanHastaService{
  FirebaseFirestore ?_instance;
  List<Autogenerated> _yatanhastaservicemodel = [];
  List<Autogenerated> getYatanHasta(){
    return _yatanhastaservicemodel;
  }
Future<void> getYaranHastaFromFirebas()async {
   _instance = FirebaseFirestore.instance;
   CollectionReference YatanHastalar = _instance!.collection("yatanHastalar");
   DocumentSnapshot snapshot = await YatanHastalar.doc().get();
   var data = snapshot.data() as Map;
   var yatanTedaviler = data['tedaviler'] as List<dynamic>;
   yatanTedaviler.forEach((element) {
     debugPrint(element.toString());
     Autogenerated cat = Autogenerated.fromJson(element);
     _yatanhastaservicemodel.add(cat);
   });
}
  
}