class Autogenerated {
  String? hastaAdi;
  String? hayvanAdi;
  String? toplamFiyat;
  String? yatisZamani;
  List<Tedaviler>? tedaviler;

  Autogenerated({this.hastaAdi, this.tedaviler,this.hayvanAdi,this.toplamFiyat,this.yatisZamani});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    hastaAdi = json['hasta_adi'];
    if (json['tedaviler'] != null) {
      tedaviler = <Tedaviler>[];
      json['tedaviler'].forEach((v) {
        tedaviler!.add(Tedaviler.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['hasta_adi'] = this.hastaAdi;
    data['hayvan_adi'] = this.hayvanAdi;
    data['yatis_zamani'] = this.yatisZamani;
    data['toplam_fiyat'] = this.toplamFiyat;

    if (this.tedaviler != null) {
      data['tedaviler'] = this.tedaviler!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Tedaviler {
  String? id;
  String? name;
  double? price;
  String? skt;
  int? stok;
  String?ustId;

  Tedaviler({this.id, this.name, this.price,this.skt,this.stok,this.ustId});

  factory Tedaviler.fromJson(Map<String, dynamic> json) {
    return Tedaviler(id: json['id'],name: json['name'],price: json['price'],skt: json['skt'],stok: json['stok'],ustId: json['id']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['price'] = this.price;
    data['skt'] = this.skt;
    data['stok'] = this.stok;
    return data;
  }
}

List<Autogenerated> test = [];
addlist(Autogenerated temp){
  test.add(temp);
}