class Autogenerated {
  String? hastaAdi;
  List<Tedaviler>? tedaviler;

  Autogenerated({this.hastaAdi, this.tedaviler});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    hastaAdi = json['hasta_adi'];
    if (json['tedaviler'] != null) {
      tedaviler = <Tedaviler>[];
      json['tedaviler'].forEach((v) {
        tedaviler!.add(new Tedaviler.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['hasta_adi'] = this.hastaAdi;
    if (this.tedaviler != null) {
      data['tedaviler'] = this.tedaviler!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Tedaviler {
  String? id;
  String? name;
  double? price;

  Tedaviler({this.id, this.name, this.price});

  Tedaviler.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    price = json['price'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['price'] = this.price;
    return data;
  }
}
